# Exploring Airbnb Market Trends

![NYC Skyline](nyc.jpg)

Welcome to New York City, one of the most-visited cities in the world. There are many Airbnb listings in New York City to meet the high demand for temporary lodging for travelers, which can be anywhere between a few nights to many months. In this project, we will take a closer look at the New York Airbnb market by combining data from multiple file types like `.csv`, `.tsv`, and `.xlsx`.

Recall that **CSV**, **TSV**, and **Excel** files are three common formats for storing data. 
Three files containing data on 2019 Airbnb listings are available to you:

**data/airbnb_price.csv**
This is a CSV file containing data on Airbnb listing prices and locations.
- **`listing_id`**: unique identifier of listing
- **`price`**: nightly listing price in USD
- **`nbhood_full`**: name of borough and neighborhood where listing is located

**data/airbnb_room_type.xlsx**
This is an Excel file containing data on Airbnb listing descriptions and room types.
- **`listing_id`**: unique identifier of listing
- **`description`**: listing description
- **`room_type`**: Airbnb has three types of rooms: shared rooms, private rooms, and entire homes/apartments

**data/airbnb_last_review.tsv**
This is a TSV file containing data on Airbnb host names and review dates.
- **`listing_id`**: unique identifier of listing
- **`host_name`**: name of listing host
- **`last_review`**: date when the listing was last reviewed

As a consultant working for a real estate start-up, you have collected Airbnb listing data from various sources to investigate the short-term rental market in New York. You'll analyze this data to provide insights on private rooms to the real estate company.

There are three files in the _data_ folder: 
airbnb_price.csv, airbnb_room_type.xlsx, airbnb_last_review.tsv.

Answer the following questions:
- What are the dates of the earliest and most recent reviews? Store these values as two separate variables with your preferred names.
- How many of the listings are private rooms? Save this into any variable.
- What is the average listing price? Round to the nearest penny and save into a variable.

Combine the new variables into one DataFrame called review_dates with four columns in the following order: first_reviewed, last_reviewed, nb_private_rooms, and avg_price. 

The DataFrame should only contain one row of values.

In [19]:
# Load numpy and pandas
import numpy as np
import pandas as pd

# Import the three file types: airbnb_price.csv, airbnb_room_type.xlsx, and airbnb_last_review.tsv.
airbnb_price = pd.read_csv('data/airbnb_price.csv')
airbnb_room_type = pd.read_excel('data/airbnb_room_type.xlsx')
airbnb_last_review = pd.read_csv('data/airbnb_last_review.tsv', sep='\t')

# Merge the three file types by the unique identifier of listing (listing_id)
# First, merge the csv and xlsx files into a file called merged_airbnb
merged_airbnb = pd.merge(airbnb_price, airbnb_room_type, on='listing_id')
# Then add the tsv file into the merged_airbnb file
merged_airbnb = pd.merge(merged_airbnb, airbnb_last_review, on='listing_id')

# show the first few rows on the file
merged_airbnb.head(10)

   listing_id        price  ...      host_name   last_review
0        2595  225 dollars  ...       Jennifer   May 21 2019
1        3831   89 dollars  ...    LisaRoxanne  July 05 2019
2        5099  200 dollars  ...          Chris  June 22 2019
3        5178   79 dollars  ...       Shunichi  June 24 2019
4        5238  150 dollars  ...            Ben  June 09 2019
5        5295  135 dollars  ...           Lena  June 22 2019
6        5441   85 dollars  ...           Kate  June 23 2019
7        5803   89 dollars  ...         Laurie  June 24 2019
8        6021   85 dollars  ...        Claudio  July 05 2019
9        6848  140 dollars  ...  Allen & Irina  June 29 2019

[10 rows x 7 columns]

## What are the dates of the earliest and most recent reviews?

In [20]:
# Converted to datetime type so can use the max() and min() functions.
merged_airbnb['last_review_date'] = pd.to_datetime(merged_airbnb['last_review'], format='%B %d %Y')

# Then find the earliest and most recent reviews
earliest_review = merged_airbnb['last_review_date'].min()
most_recent_review = merged_airbnb['last_review_date'].max()

# Print the results
print(f'The earliest review was on {earliest_review}.')
print(f'The most recent review was on {most_recent_review}.')

The earliest review was on 2019-01-01 00:00:00.
The most recent review was on 2019-07-09 00:00:00.

## How many of the listings are private rooms?

In [21]:
# View the room_type column
merged_airbnb['room_type'].unique()

array(['Entire home/apt', 'private room', 'Private room',
       'entire home/apt', 'PRIVATE ROOM', 'shared room',
       'ENTIRE HOME/APT', 'Shared room', 'SHARED ROOM'], dtype=object)

In [22]:
# Some variables in the room_type column are in lower case and some are in upper case; therefore, make the capitalization consistent
merged_airbnb['room_type'] = merged_airbnb['room_type'].str.lower()

# Then identify the number of private rooms by creating a variable called private_rooms
private_rooms = merged_airbnb[merged_airbnb['room_type'] == 'private room'].shape[0]
print(f'There are {private_rooms} private rooms.')

There are 11356 private rooms.

## What is the average listing price? 
Round to the nearest penny and save into a variable.

In [23]:
# View the price column
merged_airbnb['price'].head()

0    225 dollars
1     89 dollars
2    200 dollars
3     79 dollars
4    150 dollars
Name: price, dtype: object

In [24]:
# The prices are not numbers but text. So, convert the column to numeric values by removing the word "dollars" from each value and assigning as a float
merged_airbnb['price_in_dollars'] = merged_airbnb['price'].str.replace(' dollars', '').astype(float)

# Create a variable called avg_listing_price that is the averge (mean) listing price
avg_listing_price = merged_airbnb['price_in_dollars'].mean()

# Print the result to the nearest penny
print(f'The average listing price is ${round(avg_listing_price,2)}.')

The average listing price is $141.78.

## Combine the new variables into one DataFrame called review_dates 
The dataframe should have one row of data and four columns in the following order:
first_reviewed, last_reviewed, nb_private_rooms, and avg_price.

In [25]:
# Combine the new variables into one DataFrame called review_dates
review_dates = pd.DataFrame({
    'first_reviewed': [earliest_review],
    'last_reviewed': [most_recent_review],
    'nb_private_rooms': [private_rooms],
    'avg_price': [round(avg_listing_price, 2)]
})
print(review_dates)

  first_reviewed last_reviewed  nb_private_rooms  avg_price
0     2019-01-01    2019-07-09             11356     141.78